# Generated by Django 3.1.5 on 2021-01-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='state_provice',
            new_name='state_province',
        ),
    ]
