# Generated by Django 3.1.5 on 2021-01-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='is_chain',
            field=models.IntegerField(verbose_name=1),
        ),
    ]
